name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOMAIN: stenberg.io

jobs:
  install-and-lint:
    name: Install and run linter
    uses: ./.github/workflows/install-and-lint.yaml

  deploy:
    needs: install-and-lint
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v4

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build client
        run: pnpm build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.APP_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH Key to known_hosts
        run: |
          ssh-keyscan -H ${{ env.DOMAIN }} >> ~/.ssh/known_hosts

      - name: Rsync to server
        run: |
          rsync --delete -azr ./dist/ jonas@${{ env.DOMAIN }}:/usr/local/bin/portfolio

      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no jonas@${{ env.DOMAIN }} 'sudo systemctl restart nginx'
